version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    entrypoint: dockerize -wait tcp://db:27017 -timeout 40s ./.docker/entrypoint.sh
    container_name: ${APP_NAME}
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  db:
    image: mongo:latest
    container_name: ${APP_NAME}-db
    tty: true
    volumes:
      - ./.docker/dbdata:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    user: '1000:1000'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
